# fly.toml app configuration file generated for cold-star-5696 on 2023-11-03T14:56:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-star-5696"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
